### ISSUE TITLE
Doc Request: Add FAQ and/or Roadmap

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/SlicerVirtualReality#127]
As someone who is interested in Slicer's extended support for XR, it would be helpful to have a high-level "FAQ" section or roadmap of features intended for this module.

## Questions to Answer
- [x] Is `SlicerMixedReality` intended as the OpenXR equivalent of https://github.com/KitwareMedical/SlicerVirtualReality, which is for OpenVR? Is it anticipated that `SlicerMixedReality` will eventually reach feature parity and replace `SlicerVirtualReality` as the industry moves towards OpenXR?
- [x] What devices are planned for support by `SlicerMixedReality`? Is it planned for all devices covered by the [`VTK::RenderingOpenXR`](https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#supported-devices) module to eventually be available through SlicerMixedReality, or is only HoloLens remoting support through `VTK::RenderingOpenXRRemoting` planned?
- [x] To what degree will OpenXR features be leveraged? Will both VR and passthrough AR be available on capable devices such as the Meta Quest headsets? Will AR remoting be available for devices in addition to the Microsoft HoloLens? What input schemes will be supported?
- [x] Are there other planned features that would fit into the scope of this module, such as collaborative XR viewing?

To be clear, I am not necessarily asking for concrete answers or technical details. Any discussion that module developers could contribute to clarify the planned scope of this module and where development *may* go would be appreciated.

## References

To aid in discussion, we have recently expanded documentation for VTK supported XR devices and input mechanisms here:
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#vtkrenderingopenxr
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXRRemoting#vtkrenderingopenxrremoting
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenVR#vtkrenderingopenvr
